apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .value.appName }}
  namespace: default
  labels:
    app: {{ .value.appName }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: {{ .value.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .value.appName }}
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: devopsjourney1/mywebapp:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: myconfigmapv1.0
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
