apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.name }}
  labels:
    app: nginx
spec:
  type: {{ .Values.Service.type }}
  ports:
    - port: {{ .Values.Service.port }}
      nodePort: {{ .Values.Service.nodePort }}
      targetPort: {{ .Values.Service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: nginx
